spring.application.name=locvac
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =============================
# JWT
# =============================
jwt.secret=${JWT_SECRET}
jwt.expiration.access=900000
jwt.expiration.refresh=2592000000
jwt.expiration.mfa=300000

# =============================
# MFA
# =============================
mfa.issuer=LocVac