import { StyleSheet } from 'react-native';
import { type Colors, radii, shadows, typography } from '../theme/tokens';

export const makeStyles = (c: Colors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: c.bg,
    paddingTop: 48,
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  helpButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.bgElev,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchWrap: {
    marginTop: 4,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: c.bgElev,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: c.line,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 12,
    paddingRight: 12,
    fontSize: 14,
    color: c.ink,
  },

  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 18,
    marginBottom: 4,
  },
  sectionTitle: {
    ...typography.h2,
    color: c.ink,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: c.bgElev,
    borderWidth: 1,
    borderColor: c.line,
    maxWidth: 180,
  },
  filterButtonActive: {
    backgroundColor: c.brand,
    borderColor: c.brand,
  },
  filterButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },

  sheetOverlay: {
    flex: 1,
    backgroundColor: 'transparent',
    justifyContent: 'flex-end',
  },
  sheetContent: {
    backgroundColor: c.bgElev,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 40,
    ...shadows.lg,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: c.lineStrong,
    marginBottom: 12,
  },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  sheetTitle: {
    ...typography.h3,
    color: c.ink,
  },
  filterOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: radii.md,
    marginVertical: 2,
  },
  filterOptionActive: {
    backgroundColor: c.brandSoft,
  },
  filterOptionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: c.ink,
  },
  filterOptionSub: {
    fontSize: 12,
    color: c.ink3,
    marginTop: 2,
  },

  scroll: {
    paddingHorizontal: 16,
    paddingBottom: 30,
  },

  carrosselSection: {
    marginHorizontal: -16,
    marginTop: '5%',
    marginBottom: 12,
    paddingLeft: 16,
  },
  carrosselCard: {
    width: 280,
    marginRight: 12,
    borderRadius: radii.lg,
    overflow: 'hidden',
    backgroundColor: c.bgElev,
    borderWidth: 1,
    borderColor: c.line,
  },
  carrosselImage: {
    width: '100%',
    height: 140,
    backgroundColor: c.bgMuted,
  },
  carrosselContent: {
    padding: 12,
  },
  carrosselTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: c.ink,
    marginBottom: 4,
  },
  carrosselDescription: {
    fontSize: 12,
    color: c.ink2,
  },
  indicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
    gap: 6,
    marginRight: 16,
  },
  indicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: c.lineStrong,
  },
  indicatorActive: {
    backgroundColor: c.brand,
    width: 24,
  },

  groupSection: {
    marginTop: 18,
  },
  groupHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 10,
  },
  groupIcon: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  groupLabel: {
    ...typography.h3,
    color: c.ink,
  },
  groupSub: {
    fontSize: 11,
    color: c.ink3,
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },

  vaccineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: c.bgElev,
    borderWidth: 1,
    borderColor: c.line,
    borderRadius: radii.md,
    padding: 12,
    marginBottom: 6,
  },
  vaccineDot: {
    width: 32,
    height: 32,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  vaccineName: {
    fontSize: 14,
    fontWeight: '600',
    color: c.ink,
  },
  vaccineSub: {
    fontSize: 12,
    color: c.ink3,
    marginTop: 2,
  },

  empty: {
    marginTop: 16,
    padding: 22,
    borderRadius: radii.lg,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: c.lineStrong,
    alignItems: 'center',
  },
  emptyText: {
    color: c.ink3,
    fontSize: 13,
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: c.dimDark,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 40,
  },
  modalContent: {
    backgroundColor: c.bgElev,
    borderRadius: radii.xl,
    paddingHorizontal: 22,
    paddingTop: 18,
    paddingBottom: 26,
    width: '100%',
    maxWidth: 420,
    ...shadows.lg,
    gap: 8,
  },
  modalClose: {
    alignSelf: 'flex-end',
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: c.line,
    backgroundColor: c.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalTitle: {
    ...typography.h2,
    color: c.ink,
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 14,
  },
  modalText: {
    fontSize: 13,
    color: c.ink2,
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 26,
  },
  modalCta: {
    backgroundColor: c.brand,
    borderRadius: radii.md,
    paddingVertical: 14,
    alignItems: 'center',
  },
  modalCtaText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
});
