import { StyleSheet } from 'react-native';
import { colors, radii, spacing, typography, shadows } from '../theme/tokens';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bg,
    paddingTop: '5%',
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.md,
    paddingBottom: 130,
  },

  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.lg,
    backgroundColor: colors.bgElev,
    borderRadius: radii.lg,
    padding: spacing.lg,
    borderWidth: 1,
    borderColor: colors.line,
    marginVertical: spacing.xl,
    ...shadows.sm,
  },
  profileText: {
    flex: 1,
    gap: 4,
    marginTop: 8,
  },
  profileName: {
    ...typography.h3,
    color: colors.ink,
  },
  profileTagRow: {
    flexDirection: 'row',
    gap: 6,
  },
  profileTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.brandSoft,
    borderRadius: radii.pill,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  profileTagText: {
    ...typography.caption,
    color: colors.brandInk,
    fontWeight: '600',
  },
  profileEmail: {
    ...typography.small,
    color: colors.ink3,
  },
  section: {
    marginBottom: spacing.xl,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.md,
  },
  sectionTitle: {
    ...typography.h3,
    color: colors.ink,
    marginBottom: 2,
  },
  sectionSub: {
    ...typography.small,
    color: colors.ink3,
  },
  addButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.brand,
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
  },
  addButtonText: {
    ...typography.small,
    color: colors.white,
    fontWeight: '600',
  },

  emptyCard: {
    backgroundColor: colors.bgElev,
    borderRadius: radii.lg,
    padding: spacing.xl,
    borderWidth: 1,
    borderColor: colors.line,
    alignItems: 'center',
    gap: spacing.sm,
  },
  emptyIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyTitle: {
    ...typography.bodyLg,
    fontWeight: '600',
    color: colors.ink,
  },
  emptySub: {
    ...typography.small,
    color: colors.ink3,
    textAlign: 'center',
  },

  dependentsList: {
    gap: spacing.sm,
  },
  dependentCard: {
    backgroundColor: colors.bgElev,
    borderRadius: radii.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dependentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    flex: 1,
  },
  dependentInfo: {
    flex: 1,
  },
  dependentName: {
    ...typography.body,
    fontWeight: '600',
    color: colors.ink,
  },
  dependentMeta: {
    ...typography.small,
    color: colors.ink3,
    marginTop: 2,
  },
  dependentActions: {
    flexDirection: 'row',
    gap: 4,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: radii.md,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },

  menuCard: {
    backgroundColor: colors.bgElev,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.line,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    gap: spacing.md,
  },
  menuIconWrap: {
    width: 32,
    height: 32,
    borderRadius: radii.md,
    backgroundColor: colors.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuLabel: {
    ...typography.body,
    color: colors.ink,
    flex: 1,
  },
  menuDivider: {
    height: 1,
    backgroundColor: colors.line,
    marginLeft: spacing.md + 32 + spacing.md,
  },

  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: colors.coralSoft,
    borderRadius: radii.lg,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: colors.coralSoft,
  },
  logoutText: {
    ...typography.body,
    color: colors.coralInk,
    fontWeight: '600',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: colors.dimDark,
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  modalCard: {
    width: '100%',
    maxWidth: 380,
    maxHeight: '85%',
    backgroundColor: colors.bgElev,
    borderRadius: radii.xl,
    padding: spacing.lg,
    flexDirection: 'column',
    ...shadows.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    ...typography.h3,
    color: colors.ink,
  },
  modalClose: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.bgMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalScroll: {
    marginVertical: spacing.md,
  },
  legend: {
    ...typography.caption,
    color: colors.ink3,
    marginTop: 4,
    fontStyle: 'italic',
  },
  required: {
    color: colors.coral,
    fontWeight: '700',
  },
  inputError: {
    borderWidth: 1,
    borderColor: colors.danger,
    backgroundColor: colors.dangerSoft,
  },
  errorText: {
    ...typography.caption,
    color: colors.danger,
    marginTop: 4,
    fontWeight: '500',
  },

  photoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  photoPreview: {
    width: 64,
    height: 64,
    borderRadius: 32,
  },
  photoPlaceholder: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoActions: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  photoButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: spacing.md,
    paddingVertical: 7,
    borderRadius: radii.pill,
    backgroundColor: colors.brand,
  },
  photoButtonGhost: {
    backgroundColor: colors.bgMuted,
    borderWidth: 1,
    borderColor: colors.line,
  },
  photoButtonText: {
    ...typography.small,
    fontWeight: '600',
    color: colors.white,
  },
  photoButtonTextGhost: {
    color: colors.ink2,
  },

  fieldGroup: {
    gap: 4,
    marginBottom: spacing.md,
  },
  label: {
    ...typography.small,
    fontWeight: '600',
    color: colors.ink,
  },
  input: {
    backgroundColor: colors.bgMuted,
    borderRadius: radii.sm + 3, // 11
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: spacing.md,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.ink,
  },
  sexRow: {
    flexDirection: 'row',
    gap: 8,
  },
  sexChip: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: radii.sm + 3,
    backgroundColor: colors.bgMuted,
    borderWidth: 1,
    borderColor: colors.line,
  },
  sexChipActive: {
    backgroundColor: colors.brand,
    borderColor: colors.brand,
  },
  sexChipText: {
    ...typography.small,
    fontWeight: '600',
    color: colors.ink,
  },
  sexChipTextActive: {
    color: colors.white,
  },
  dateButton: {
    backgroundColor: colors.bgMuted,
    borderRadius: radii.sm + 3,
    borderWidth: 1,
    borderColor: colors.line,
    paddingHorizontal: spacing.md,
    paddingVertical: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  dateButtonText: {
    ...typography.body,
    color: colors.ink4,
  },
  dateButtonTextFilled: {
    ...typography.body,
    color: colors.ink,
  },
  pickerDropdown: {
    marginTop: 6,
    backgroundColor: colors.bgElev,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.line,
    maxHeight: 200,
    overflow: 'hidden',
  },
  pickerScroll: {
    maxHeight: 200,
  },
  pickerOption: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.line,
  },
  pickerOptionActive: {
    backgroundColor: colors.brandSoft,
  },
  pickerOptionText: {
    ...typography.body,
    color: colors.ink,
  },
  pickerOptionTextActive: {
    fontWeight: '600',
    color: colors.brandInk,
  },
  modalActions: {
    flexDirection: 'row',
    gap: spacing.md,
    marginTop: spacing.sm,
  },
  cancelButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.bgElev,
  },
  cancelButtonText: {
    ...typography.body,
    fontWeight: '600',
    color: colors.ink2,
  },
  saveButton: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    borderRadius: radii.md,
    backgroundColor: colors.brand,
  },
  saveButtonText: {
    ...typography.body,
    fontWeight: '600',
    color: colors.white,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
});
